### ISSUE TITLE
프론트 자바스크립트에서 연결된 URL 찾는 더 쉬운 방법

### ISSUE THREAD

**Issue by kimdev0206** [javascript-unitied-project/chat-server#1]
https://github.com/javascript-unitied-project/main-server/blob/d84cddc5243244149c9fd679b2564f156ceffbc3/programs/public/js/totaldata.js#L47

이거로 바꿔보세요. 정규표현식쓰는 함수말고 따로 내장모듈이 있네요!

**Comment by JiYongKim-A** [comment]
확인 해보겠습니다!!!

**Comment by JiYongKim-A** [comment]
![param](https://user-images.githubusercontent.com/81874493/123225648-e056ad00-d50d-11eb-8916-7dc117130ec7.PNG)
-- 위의 방식으로 쿼리 값 출력 가능합니다.
    이 방법으로 사용하겠습니다.
